CREATE TABLE users (
	id BLOB NOT NULL PRIMARY KEY,
	username TEXT NOT NULL UNIQUE COLLATE NOCASE,
	password TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sessions (
	id BLOB NOT NULL PRIMARY KEY,
	user_id BLOB NOT NULL,
	expires TIMESTAMP NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE conversations (
	id BLOB NOT NULL PRIMARY KEY
);

CREATE TABLE messages (
	id BLOB NOT NULL PRIMARY KEY
);
